main:main.cpp glad/glad.c Player.cpp Table.cpp ModelImporter.cpp
	g++ -std=c++11 main.cpp glad/glad.c Player.cpp Table.cpp ModelImporter.cpp Game.cpp -o game -lSDL2 -lSDL2main -I/usr/local/Cellar/sdl2/2.0.8/include/SDL2/ -framework OpenGL

clean:
	rm game